version: "2"
services:
  app:
    container_name: monitor_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - APPLICATION_PORT=3000
      - APPLICATION_HOST=localhost
      - DATABASE_HOST=mongo
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_PORT=27017
      - DATABASE_NAME=monitorapp
      - JWT_SECRET=secretsecret
      - MAILGUN_API_KEY=1826c00a7e7cdfa98f82439979cac672-27a562f9-1ec43e4b
      - MAILGUN_DOMAIN=sandbox35dc7696a1834f2880ff5a1e161878ab.mailgun.org

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - ~/mongo:/data/db
      